<section class="container">
<h1>Осенний weekend в Риге</h1>
</section>
<section class="container">
<p><em><strong>Соблазненные причудливыми оттенками Старого города, многие едут в Ригу, чтобы погрузиться в эту прекрасно реконструированную средневековую атмосферу. Но как ни привлекателен этот объект всемирного наследия ЮНЕСКО, трудно судить обо всем городе, посетив только один район. Давайте выясним, какая Рига на самом деле.</strong></em></p>
<!--more-->

<p>За современными постройками Риги часто скрываются старые и шероховатые районы, которые заставляют взглянуть на город с другой стороны. Старые заброшенные кварталы представляют собой улей творческой деятельности, где старые деревянные дома превратили в дизайнерские магазины, богемные бары, кафе третьего поколения, рестораны современной кухни, места для творчества и арт-пространства.

Видно, что Рига всеми силами пытается избавиться от звания "постсоветского" государства. Все, кто приезжает в этот город в поисках ярких пережитков советской эпохи, рискует здесь ничего этого не заметить. Советское прошлое здесь тщательно похоронено.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/okm59ttoy7zbs0u/_DSC2739.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Один из старых районов Риги" src="https://dl.dropboxusercontent.com/s/okm59ttoy7zbs0u/_DSC2739.jpg" alt="Один из старых районов Риги" width="700" height="469" /></a></p>
<p style="text-align: center;"><em>Один из старых районов Риги</em></p>
<p>Город вырос на торговом пути Ганзейского союза по реке Даугаве в 13-15 веках, а затем до самого 1710 года переходил из рук в руки. Сначала он стал частью Священной Римской империи, затем Речи Посполитой, Королевства Швеции и, наконец, Российской империи.

Независимость была достигнута в 1918 году под контролем Германии, но только на короткое время. В 1940 году Латвия стала частью Советского Союза, а затем была оккупирована нацистской Германией в 1941-1944 годах, прежде чем Советская Красная Армия вернулась в 1944 году для восстановления власти. В 1991 году Латвия получила независимость.

История навсегда отразилась в облике этого города.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/s3vaazbwctr8sjx/_DSC2760.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" src="https://dl.dropboxusercontent.com/s/s3vaazbwctr8sjx/_DSC2760.jpg" alt="Часовая башня Рижского центрального вокзала" width="700" height="469" /></a></p><p style="text-align: center;"><em>Часовая башня Рижского центрального вокзала</em></p>
<p>Можно часами бродить и наслаждаться Ригой. По пути вы обязательно наткнетесь на комиссионные магазины, антикварные магазины, скрытые от глаз дворы и граффити.
Эта прогулка необходима для того, чтобы понять, как Рига развивалась веками, как новая жизнь бьет ключом среди обветшалых районов и ветхих фасадов старой имперской России.</p>

<p style="text-align: center;"><iframe style="border: 0;" src="https://www.google.com/maps/embed?pb=!4v1573874297112!6m8!1m7!1sQlKSp-D1iQoLVZWAAzTtjA!2m2!1d56.95113625770986!2d24.13489401137648!3f125.62731113311177!4f-0.036403333091172385!5f0.7820865974627469" width="1200" height="469" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p style="text-align: center;"><em>Один из старых районов Риги</em></p>

<p>Я советую свою прогулку начинать с посещения <strong>Рижского рынка</strong>. Не зря же говорят "скажи мне, что ты ешь, и я скажу, кто ты есть". 

Рижский центральный рынок расположен в нескольких сотнях метров от Старого города на берегу реки Даугава, в непосредственной близости от международного автовокзала и центрального железнодорожного вокзала. Это одна из крупнейших торговых площадок в Восточной Европе, и каждый день там делают покупки более 80 000 человек!</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/sfvgmdfp8yna31b/_DSC3207.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Рижский Центральный рынок" src="https://dl.dropboxusercontent.com/s/sfvgmdfp8yna31b/_DSC3207.jpg" alt="Рижский Центральный рынок" width="700" height="469" /></a></p><p style="text-align: center;"><em>Рижский Центральный рынок</em></p>
<p>Впечатляющие здания на рынке были построены в 1920-х годах для производства военных дирижаблей. Позже они были преобразованы в нынешние продовольственные павильоны.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/5rqeiny9qapgjkk/_DSC3210.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="На Рижском Центральном рынке" src="https://dl.dropboxusercontent.com/s/5rqeiny9qapgjkk/_DSC3210.jpg" alt="На Рижском Центральном рынке" width="700" height="469" /></a></p><p style="text-align: center;"><em>Чайка на Рижском рынке
</em></p>
<p>Центральный рынок - это то место, куда можно пойти, если вы хотите продегустировать продукты местного производства. <strong>Я советую попробовать рижский сыр, квас, рыбу, особенно деликатес-миногу.</strong> Так же не помешает прикупить и сладостей.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/kqu6ilaxbjx72ng/_DSC3226.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Рижский Центральный рынок" src="https://dl.dropboxusercontent.com/s/kqu6ilaxbjx72ng/_DSC3226.jpg" alt="Рижский Центральный рынок" width="700" height="469" /></a></p><p style="text-align: center;"><em>Рижский Центральный рынок</em></p>
<p><strong>Не стоит забывать про знаменитый Рижский бальзам и шоколад производства фирмы Laima.</strong>

Цены на продукты в Латвии, кстати, ничем не отличаются от российских.

После того, как вы отведали местных деликатесов, можно пойти исследовать Старый город, который является значительной частью города и краеугольным камнем рижского туризма. По дороге следует заскочить в самое романтичное и тихое место Риги - <strong>Верманский парк.</strong> </p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/p3itrrs591573gw/_DSC2768.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Один из старых районов Риги" src="https://dl.dropboxusercontent.com/s/p3itrrs591573gw/_DSC2768.jpg" alt="Рижский цирк" width="700" height="469" /></a></p><p style="text-align: center;"><em>Рижский цирк</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/1835pujwqy3htg8/_DSC2773.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Один из старых районов Риги" src="https://dl.dropboxusercontent.com/s/1835pujwqy3htg8/_DSC2773.jpg" alt="Трамвай на улице Krišjāņa Barona" width="700" height="469" /></a></p><p style="text-align: center;"><em>Трамвай на улице Krišjāņa Barona</em></p>
<p>Напротив Верманского парка располагаются <strong>Музыкальная академия им. Я.Витола</strong>, где когда-то проходил обучение композитор Раймонд Паулс, и <strong>Латвийский университет</strong>.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/j2k40ry2ns322d9/_DSC2784.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Верманский парк" src="https://dl.dropboxusercontent.com/s/j2k40ry2ns322d9/_DSC2784.jpg" alt="Верманский парк" width="700" height="469" /></a></p><p style="text-align: center;"><em>Верманский парк</em></p>
<p>Нагулявшись по парку, обязательно пройдите по улице Меркеля до пересечения с бульваром Бривибас и поверните направо к <strong>Памятнику Свободы.</strong>

Памятник Свободы высотой 42 метра символизирует национальное единство, независимость и свободу в Латвии. Его создание полностью финансировалось гражданами Латвии как памятник тем, кто погиб в борьбе за независимость.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/r4ra2bff5wyu4x9/_DSC2864.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Памятник Свободы" src="https://dl.dropboxusercontent.com/s/r4ra2bff5wyu4x9/_DSC2864.jpg" alt="Памятник Свободы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Памятник Свободы</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/truzrxj187zc7cd/_DSC2867.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Памятник Свободы" src="https://dl.dropboxusercontent.com/s/truzrxj187zc7cd/_DSC2867.jpg" alt="Памятник Свободы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Памятник Свободы</em></p>
<p>Женщина Свобода на вершине - известная как «Милда» - держит три звезды, которые символизируют исторические регионы Латвии. У основания памятника расположены скульптуры и барельефы, изображающие историю и культуру Латвии.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/xi3k4077kiem4z0/_DSC2846.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Памятник Свободы" src="https://dl.dropboxusercontent.com/s/xi3k4077kiem4z0/_DSC2846.jpg" alt="Памятник Свободы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Памятник Свободы</em></p>
<p style="text-align: center;"><iframe src="https://www.youtube.com/embed/bWoFZaJZFyA" width="1100" height="500" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>

<p>Статуя была воздвигнута в 1935 году, всего за пять лет до прихода Советской власти. Примечательно, что советская власть не разрушила памятник, но запрещала его посещать. Любой, кто приносил цветы к памятнику, наказывался. Теперь два солдата стоят на страже у Памятника Свободы в течение дня, и ежечасно с 9 до 18 часов можно наблюдать смену караула.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/1ifaaoh16a0z3cu/_DSC2855.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Почетный караул у Памятника Свободы" src="https://dl.dropboxusercontent.com/s/1ifaaoh16a0z3cu/_DSC2855.jpg" alt="Почетный караул у Памятника Свободы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Почетный караул у Памятника Свободы</em></p>
<p>Зеленая зона с декоративными насаждениями и каменными элементами - это <strong>Парк Бастионной горки</strong>. Местные жители называют его просто - Бастионка. А четырехгранный кремово-коричневый столб с надписями Laima и швейцарскими часами наверху - это самые романтичные рижские <strong>часы "Лайма"</strong>.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/na00tmtvz72mw17/_DSC2875.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Бастионная горка" src="https://dl.dropboxusercontent.com/s/na00tmtvz72mw17/_DSC2875.jpg" alt="Бастионная горка" width="700" height="469" /></a></p><p style="text-align: center;"><em>Бастионная горка</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/8b2wmywwbnewwz6/_DSC2877.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Часы " src="https://dl.dropboxusercontent.com/s/8b2wmywwbnewwz6/_DSC2877.jpg" alt="Часы " width="700" height="469" /></a></p><p style="text-align: center;"><em>Часы "Лайма"</em></p>
<p>Наконец, перейдя бульвар Аспазияс, мы попадаем в <strong>Старый город</strong>.

Старый город Риги — это район, который до сих пор напоминает живой музей средневековой истории города, где можно найти небольшие части старых оборонительных стен и башни. И, несмотря на то, что почти все исторические здания были восстановлены после войны из-за обширного повреждения бомбами, вас ждет увлекательная прогулка в 800-летнюю историю города.</p>
<ul>
 	<li><strong>Пороховая башня.</strong><strong> </strong>Первоначально построенная в 1330 году, Песчаная башня была одной из более чем 20 огромных башен, которые были частью системы обороны города.
Нынешний дизайн башни датируется 1650 годом, тогда она стала известна как Пороховая башня, так как служила хранилищем для запасов пороха.
Пороховая башня в настоящее время является частью Военного музея.</li>
</ul>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/30s8841v8b5dz8n/_DSC2891.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Улица Vaļņu и Пороховая Башня" src="https://dl.dropboxusercontent.com/s/30s8841v8b5dz8n/_DSC2891.jpg" alt="Улица Vaļņu и Пороховая Башня" width="700" height="469" /></a></p><p style="text-align: center;"><em>Улица Vaļņu и Пороховая Башня</em></p>
<p style="text-align: center;"><iframe style="border: 0;" src="https://www.google.com/maps/embed?pb=!4v1573885147222!6m8!1m7!1s-rh1vEluxEShpAxhYk8sSQ!2m2!1d56.9513767921296!2d24.10962417362065!3f279.08206971106796!4f18.310713799629966!5f0.861371717174487" width="700" height="469" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p style="text-align: center;"><em>Пороховая Башня</em></p>

<ul>
 	<li><strong>Шведские ворота. </strong>Средневековый город Рига был окружен крепкими стенами, защищавшими его от нападавших. Единственные городские ворота, оставшиеся на сегодня, - это Шведские ворота, которые датируются 1698 годом, когда шведы правили городом. Сразу за стенами находятся небольшие оригинальные средневековые улочки.</li>
</ul>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/wv2ggphww0vjsq1/_DSC2905.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Казармы Якова" src="https://dl.dropboxusercontent.com/s/wv2ggphww0vjsq1/_DSC2905.jpg" alt="Казармы Якова" width="700" height="469" /></a></p><p style="text-align: center;"><em>Казармы Якова</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/x1cxr5il1ypih3g/_DSC2907.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" src="https://dl.dropboxusercontent.com/s/x1cxr5il1ypih3g/_DSC2907.jpg" alt="" width="700" height="469" /></a></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/17lz7e0y7lg3wyn/_DSC2909.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Шведские ворота" src="https://dl.dropboxusercontent.com/s/17lz7e0y7lg3wyn/_DSC2909.jpg" alt="Шведские ворота" width="700" height="469" /></a></p><p style="text-align: center;"><em>Шведские ворота</em></p>

<ul>
 	<li><strong>Три брата. </strong>Одни из самых известных зданий в Старом городе - это знаменитые «Три брата», каждое из которых было построено в разные века - 15, 16 и 17.</li>
</ul>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/rfpn7pmr71rqsy6/_DSC2919.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Три брата" src="https://dl.dropboxusercontent.com/s/rfpn7pmr71rqsy6/_DSC2919.jpg" alt="Три брата" width="700" height="469" /></a></p><p style="text-align: center;"><em>Три брата</em></p>

<ul>
 	<li><strong>Набережная Даугавы. </strong>Просто потрясающее место для пеших неспешных прогулок. С Вантового моста открывается потрясающий вид на Рижский замок - резиденцию президента Латвии.</li>
</ul>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/88qvypghpvjfpsa/_DSC2942.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вдоль набережной Даугавы" src="https://dl.dropboxusercontent.com/s/88qvypghpvjfpsa/_DSC2942.jpg" alt="Вдоль набережной Даугавы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вдоль набережной Даугавы</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/5ap99ob8fc5o77s/_DSC2966.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вдоль набережной Даугавы" src="https://dl.dropboxusercontent.com/s/5ap99ob8fc5o77s/_DSC2966.jpg" alt="Вдоль набережной Даугавы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вдоль набережной Даугавы</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/w7dst5b7jvfuna7/_DSC2952.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вдоль набережной Даугавы" src="https://dl.dropboxusercontent.com/s/w7dst5b7jvfuna7/_DSC2952.jpg" alt="Вдоль набережной Даугавы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вдоль набережной Даугавы</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/bjnzbi61bhf6ycg/_DSC2964.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вдоль набережной Даугавы" src="https://dl.dropboxusercontent.com/s/bjnzbi61bhf6ycg/_DSC2964.jpg" alt="Вдоль набережной Даугавы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вдоль набережной Даугавы</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/a1a3zlmgn9w6w44/_DSC2969.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вдоль набережной Даугавы" src="https://dl.dropboxusercontent.com/s/a1a3zlmgn9w6w44/_DSC2969.jpg" alt="Вдоль набережной Даугавы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вдоль набережной Даугавы</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/n4ztryqcp3ug1rq/_DSC2995.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вдоль набережной Даугавы" src="https://dl.dropboxusercontent.com/s/n4ztryqcp3ug1rq/_DSC2995.jpg" alt="Вдоль набережной Даугавы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вдоль набережной Даугавы</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/uayswi7zd6qj5xc/_DSC2999.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вдоль набережной Даугавы" src="https://dl.dropboxusercontent.com/s/uayswi7zd6qj5xc/_DSC2999.jpg" alt="Вдоль набережной Даугавы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вдоль набережной Даугавы</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/8i2aw9gmabe2mxd/_DSC3006.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вдоль набережной Даугавы" src="https://dl.dropboxusercontent.com/s/8i2aw9gmabe2mxd/_DSC3006.jpg" alt="Вдоль набережной Даугавы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вдоль набережной Даугавы</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/aek4b0fxz0vh2qs/_DSC3015.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вдоль набережной Даугавы" src="https://dl.dropboxusercontent.com/s/aek4b0fxz0vh2qs/_DSC3015.jpg" alt="Вдоль набережной Даугавы" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вдоль набережной Даугавы</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/qvyfy7y7xu6mgit/_DSC2988.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вид на Рижский замок" src="https://dl.dropboxusercontent.com/s/qvyfy7y7xu6mgit/_DSC2988.jpg" alt="Вид на Рижский замок" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вид на Рижский замок</em></p>

<ul>
 	<li><strong>Домская площадь. </strong>Мрачноватый кирпичный комплекс с темной крышей и высокой барочной многогранной башней с часами и петушком на флигеле-это Домский собор. Он был построен в 13-м веке как резиденция основателя города епископа Альберта.
В Доме радио располагаются Латвийское радио и несколько частных радиостанций.
Одна из них, "Домская площадь", вещает на русском языке. Известно, что радиовещание в Риге организовал Я.Линтерс в 1924 году. И с 1 ноября 1925 года в эфире звучат слова: "Runa Riga!" (Говорит Рига!).</li>
</ul>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/07pt4bxno2e8j1a/_DSC3031.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Домский собор" src="https://dl.dropboxusercontent.com/s/07pt4bxno2e8j1a/_DSC3031.jpg" alt="Домский собор" width="700" height="469" /></a></p><p style="text-align: center;"><em>Домский собор</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/8g2ol5yvg19jfvo/_DSC3048.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Домский собор" src="https://dl.dropboxusercontent.com/s/8g2ol5yvg19jfvo/_DSC3048.jpg" alt="Домский собор" width="700" height="469" /></a></p><p style="text-align: center;"><em>Домский собор</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/2exippqo889rc28/_DSC3034.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Дом радио" src="https://dl.dropboxusercontent.com/s/2exippqo889rc28/_DSC3034.jpg" alt="Дом радио" width="700" height="469" /></a></p><p style="text-align: center;"><em>Дом радио</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/vmiiqopcpcfiic9/_DSC3049.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Домская площадь" src="https://dl.dropboxusercontent.com/s/vmiiqopcpcfiic9/_DSC3049.jpg" alt="Домская площадь" width="700" height="469" /></a></p><p style="text-align: center;"><em>Домская площадь</em></p>

<ul>
 	<li><strong>Бейкер-стрит и Цветочная улица. </strong>Старая Рига часто присутствовала в кадре кинематографа: средневековые дома, соборы 12-16 веков, булыжные мостовые и площади. Рыцарь Айвенго, Шерлок Холмс, Доктор Ватсон, Штирлиц и профессор Плейшнер-все отметились здесь.
Священный трепет у киноманов вызывают фильмы "Семнадцать мгновений весны" и "Приключения Шерлока Холмса и доктора Ватсона". Пройтись по знаменитой Бейкер-стрит или Цветочной улице желает каждый уважающий себя турист.</li>
</ul>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/htid6tm1208p0gq/_DSC3070.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Улица Jauniela" src="https://dl.dropboxusercontent.com/s/htid6tm1208p0gq/_DSC3070.jpg" alt="Улица Jauniela" width="700" height="469" /></a></p><p style="text-align: center;"><em>Улица Jauniela</em></p>
<p>А вот то самое окно из фильма "Семнадцать мгновений весны", но, как видите, горшка с цветком там уже нет.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/f99uw4b9miznwj6/_DSC3058.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Окно из фильма Семнадцать мгновений весны" src="https://dl.dropboxusercontent.com/s/f99uw4b9miznwj6/_DSC3058.jpg" alt="Окно из фильма Семнадцать мгновений весны" width="700" height="469" /></a></p><p style="text-align: center;"><em>Окно из фильма "Семнадцать мгновений весны"</em></p>
<p>Для тех же, кто подзабыл, небольшой видеоотрывок из фильма:</p>

<p style="text-align: center;"><iframe src="https://www.youtube.com/embed/ZHiF7EPn6QA" width="700" height="469" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>

<p>Здесь же, неподалеку, располагается квартира Шерлока Холмса.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/54mmg88d5at5zxp/_DSC3057.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Дом Шерлока Холмса (слева)" src="https://dl.dropboxusercontent.com/s/54mmg88d5at5zxp/_DSC3057.jpg" alt="Дом Шерлока Холмса (слева)" width="700" height="469" /></a></p><p style="text-align: center;"><em>Дом Шерлока Холмса (слева)</em></p>
<p>Сравните:</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/ggv4bgzqahjt7t5/12.jpeg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Дом Шерлока Холмса (кадр из фильма)" src="https://dl.dropboxusercontent.com/s/ggv4bgzqahjt7t5/12.jpeg" alt="Дом Шерлока Холмса (кадр из фильма)" width="700" height="469" /></a></p><p style="text-align: center;"><em>Дом Шерлока Холмса (кадр из фильма)</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/0dbvojd15ptache/_DSC3053.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Улица Jauniela" src="https://dl.dropboxusercontent.com/s/0dbvojd15ptache/_DSC3053.jpg" alt="Улица Jauniela" width="700" height="469" /></a></p><p style="text-align: center;"><em>Улица Jauniela</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/rykalwvgdkns0vu/_DSC3074.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Улица Rozena" src="https://dl.dropboxusercontent.com/s/rykalwvgdkns0vu/_DSC3074.jpg" alt="Улица Rozena" width="700" height="469" /></a></p><p style="text-align: center;"><em>Улица Rozena</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/6yrjewz5xdrja8j/_DSC3088.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Улица Rozena" src="https://dl.dropboxusercontent.com/s/6yrjewz5xdrja8j/_DSC3088.jpg" alt="Улица Rozena" width="700" height="469" /></a></p><p style="text-align: center;"><em>Улица Rozena</em></p>

<table>
<tbody>
<tr >
<td><p><a class="a" href="https://dl.dropboxusercontent.com/s/f3wfzsovdtmy7f8/_DSC3051.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Улица Rozena" src="https://dl.dropboxusercontent.com/s/f3wfzsovdtmy7f8/_DSC3051.jpg" alt="Улица Rozena" width="277" height="370" /></a></p><p style="text-align: center;"><em>Улица Rozena</em></td>
<td><p><a class="a" href="https://dl.dropboxusercontent.com/s/se3jmuicw5hpid3/_DSC3071.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Улица Rozena" src="https://dl.dropboxusercontent.com/s/se3jmuicw5hpid3/_DSC3071.jpg" alt="Улица Rozena" width="279" height="372" /></a></p><p style="text-align: center;"><em>Улица Rozena</em></td>
<td><p><a class="a" href="https://dl.dropboxusercontent.com/s/rslpythabz5awd2/_DSC3054.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Улица Krāmu" src="https://dl.dropboxusercontent.com/s/rslpythabz5awd2/_DSC3054.jpg" alt="Улица Krāmu" width="279" height="372" /></a></p><p style="text-align: center;"><em>Улица Krāmu</em></td>
</tr>
</tbody>
</table>
<ul>
 	<li><strong>Дом Черноголовых. </strong>Дом Черноголовых-знаковое здание в Риге! Первоначально здание было построено немецкими купцами в 14 веке, но затем было полностью разрушено во время Второй мировой войны. Нынешнее здание было реконструировано в период с 1995 по 1999 год.</li>
</ul>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/uj9k7g373fj9rph/_DSC3099.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Дом Черноголовых" src="https://dl.dropboxusercontent.com/s/uj9k7g373fj9rph/_DSC3099.jpg" alt="Дом Черноголовых" width="700" height="469" /></a></p><p style="text-align: center;"><em>Дом Черноголовых</em></p>
<p>Здание использовалось Обществом Черноголовых, гильдией состоятельных торговцев и их подмастерьев. Многие из них были немецкого происхождения и путешествовали по всему миру, привозя экзотические товары. Им приходилось часто иметь дело с пиратами и грабителями, поэтому они выбрали Сен-Мориса своим покровителем, которого традиционно изображали в доспехах черного рыцаря, это дало имя их гильдии.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/53unhuu10m54gss/_DSC3107.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Дом Черноголовых" src="https://dl.dropboxusercontent.com/s/53unhuu10m54gss/_DSC3107.jpg" alt="Дом Черноголовых" width="700" height="469" /></a></p><p style="text-align: center;"><em>Дом Черноголовых</em></p>
<p>Сейчас Дом Черноголовых открыт для посещения,там можно увидеть ряд исторических экспонатов, а также предметы членов гильдии, в том числе табакерки, столовое серебро и керамику. На Ратушной площади можно увидеть статую рыцаря Роланда,-это копия. Оригинал хранится в церкви Святого Петра.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/8nh8c7vqr1m1yyw/_DSC3100.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Статуя Рыцаря Роланда" src="https://dl.dropboxusercontent.com/s/8nh8c7vqr1m1yyw/_DSC3100.jpg" alt="Статуя Рыцаря Роланда" width="700" height="469" /></a></p><p style="text-align: center;"><em>Статуя Рыцаря Роланда</em></p>

<ul>
 	<li><strong>Смотровая площадка Церкви Святого Петра. </strong>Лучшая смотровая площадка. Изначально готическая башня была построена в 15 веке, но рухнула в 1666 году, а затем была перестроена в 1690 году в стиле барокко.</li>
</ul>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/3tnnre0ny5y8srx/_DSC3124.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Церковь Святого Петра" src="https://dl.dropboxusercontent.com/s/3tnnre0ny5y8srx/_DSC3124.jpg" alt="Церковь Святого Петра" width="700" height="469" /></a></p><p style="text-align: center;"></p><p style="text-align: center;"><em>Церковь Святого Петра</em></p>
<p>Когда-то это была самая высокая деревянная конструкция в мире, но в 1721 году в нее ударила молния, и она сгорела. Полностью востановлена она была в 1971 году.
Поднимитесь на лифтовом подъемнике на высоту 72 метров на панорамную смотровую площадку, откуда открывается великолепный вид на Старый город, Центральный рынок и реку.

<strong>Стоимость посещения - 9 €.</strong></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/z29y5dtgowckqa7/_DSC3164.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вид со смотровой площадки Церкви Святого Петра" src="https://dl.dropboxusercontent.com/s/z29y5dtgowckqa7/_DSC3164.jpg" alt="Вид со смотровой площадки Церкви Святого Петра" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вид со смотровой площадки Церкви Святого Петра</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/xb4f8p9ua8wwmxk/_DSC3125.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Вид со смотровой площадки Церкви Святого Петра" src="https://dl.dropboxusercontent.com/s/xb4f8p9ua8wwmxk/_DSC3125.jpg" alt="Вид со смотровой площадки Церкви Святого Петра" width="700" height="469" /></a></p><p style="text-align: center;"><em>Вид со смотровой площадки Церкви Святого Петра</em></p>
<p style="text-align: center;"><iframe style="border: 0;" src="https://www.google.com/maps/embed?pb=!4v1573913209233!6m8!1m7!1sCAoSLEFGMVFpcE9aeUp4T2NmNmRSSldrQVR0YnBCOWZXeWllWVhjMXY5ZC1mc3d1!2m2!1d56.9475667!2d24.1091217!3f161.6943413717324!4f-18.822201986139007!5f0.7820865974627469" width="1200" height="469" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>
<p style="text-align: center;"><em>Вид со смотровой площадки Церкви Святого Петра</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/6mynjky61krjjak/_DSC3198.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Памятник Бременским музыкантам" src="https://dl.dropboxusercontent.com/s/6mynjky61krjjak/_DSC3198.jpg" alt="Памятник Бременским музыкантам" width="700" height="469" /></a></p><p style="text-align: center;"><em>Памятник Бременским музыкантам</em></p>
<p>После посещения Старого города Риги советую съездить в еще одно интересное и <strong>атмосферное место, где река Даугава впадает в Рижский залив</strong>. Для этого вам надо будет купить билет на автобус номер 24 и ехать до конечной остановки Mangaļsala. Ехать придется около часа, но, поверьте мне, это того стоит. <strong>Билет на автобус, если вы покупаете его у водителя, выйдет вам в 2€.</strong> Я же советую вам покупать билет до поездки в специальных автоматах или киосках "Narvessen", тогда билет обойдется вам 1,15€.

Чтобы лучше ориентироваться в общественном транспорте Риги, советую Вам посетить сайт <a href="https://www.rigassatiksme.lv/ru/" rel="nofollow"><strong>Rīgas satiksme</strong></a>. Сайт имеет русскую версию и здорово помогает спланировать маршрут.

От остановки Mangaļsala нужно идти по направлению к маяку Мангальсала порядка 15 минут.</p>

<script type="text/javascript" charset="utf-8" async="" src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A16b520cfd19904a46861de067b7c9cdbb95441e9da97b8ec6fcaf335dae61910&amp;width=100%25&amp;height=469&amp;lang=ru_RU&amp;scroll=true"></script>
<p><p>
<p>Атмосфера места будоражит чувства: шквальный, влажный морской воздух, шум волн, маяк, лебеди скользящие по глади Рижского залива... Все это меркнет перед видом бурной и могучей реки Даугавы, которая растворяется в спокойствии Балтийского моря, на это стоит посмотреть хотя бы раз в жизни, а лучше вернуться сюда еще не раз.</p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/ai7tb0r2v5rd0vi/_DSC3959.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Рижский залив" src="https://dl.dropboxusercontent.com/s/ai7tb0r2v5rd0vi/_DSC3959.jpg" alt="Рижский залив" width="700" height="469" /></a></p><p style="text-align: center;"><em>Рижский залив</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/miw2zvcxh23wjnz/_DSC3891.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Рижский залив" src="https://dl.dropboxusercontent.com/s/miw2zvcxh23wjnz/_DSC3891.jpg" alt="Рижский залив" width="700" height="469" /></a></p><p style="text-align: center;"><em>Рижский залив</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/fzjij0yrdldqiua/_DSC3921.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Лебеди в Рижском заливе" src="https://dl.dropboxusercontent.com/s/fzjij0yrdldqiua/_DSC3921.jpg" alt="Лебеди в Рижском заливе" width="700" height="469" /></a></p><p style="text-align: center;"><em>Лебеди в Рижском заливе</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/mx5bxemxm63zpl9/_DSC3958.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Лебеди в Рижском заливе" src="https://dl.dropboxusercontent.com/s/mx5bxemxm63zpl9/_DSC3958.jpg" alt="Лебеди в Рижском заливе" width="700" height="469" /></a></p><p style="text-align: center;"><em>Лебеди в Рижском заливе</em></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/4fscuousx03aun6/_DSC3930.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Маяк Мангальсала" src="https://dl.dropboxusercontent.com/s/4fscuousx03aun6/_DSC3930.jpg" alt="Маяк Мангальсала" width="700" height="469" /></a></p><p style="text-align: center;"><em>Маяк Мангальсала. Слева от маяка - река Даугава, а справа - Рижский залив.
</em></p>
<p>Из числа рижских музеев я бы посоветовал посетить самый интересный, на мой взгляд, среди них-<strong>Рижский моторный музей(<a href="http://www.motormuzejs.lv/index.php/ru/" rel="nofollow">Rīgas Motormuzejs</a>)</strong></p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/dtqjhpehed4666o/_DSC4031.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Рижский моторный музей" src="https://dl.dropboxusercontent.com/s/dtqjhpehed4666o/_DSC4031.jpg" alt="Рижский моторный музей" width="700" height="469" /></a></p><p style="text-align: center;"><em>Рижский моторный музей</em></p>
<p>В музее представлена вся история автомобилестроения от самых её истоков. Особо интересны кремлевская и спортивная коллекции. Выставка будет интересно всем от мала до велика. <strong>Стоимость взрослого билета 10€.</strong><p>
<p style="text-align: center;"><a class="a" href="https://dl.dropboxusercontent.com/s/2yp0e6m78fdofwr/_DSC4124.jpg" target="_blank" rel="nofollow noopener noreferrer"><img class="aligncenter" title="Спортивная коллекция. Рижский моторный музей" src="https://dl.dropboxusercontent.com/s/2yp0e6m78fdofwr/_DSC4124.jpg" alt="Спортивная коллекция. Рижский моторный музей" width="700" height="469" /></a></p><p style="text-align: center;"><em>Спортивная коллекция. Рижский моторный музей</em></p>
<p><strong>Надеюсь, вам так же, как и мне, понравится этот чудесный город. Здесь вы всегда найдете, чем себя занять и как весело провести время. А я отправляюсь в Сигулду. До скорой встречи!</strong></p>
</section>